---
  - name: Install percona server 5.7 for Debian
    command: echo "Install Percona Server 5.7"

  - name: install Percona Server 5.7 packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-server-5.7
      - percona-server-test-5.7
      - percona-server-5.7-dbg
      - percona-server-source-5.7
      - percona-server-tokudb-5.7
      - percona-server-rocksdb-5.7
    when: ansible_os_family == "Debian"

