  - name: remove the percona RHEL packages
    yum: name=percona-* state=absent 
    ignore_errors: True

  - name: remove the Percona RHEL packages caps
    yum:  name=Percona-* state=absent
    ignore_errors: True

  - name: remove the Percona yum repositories
    yum: name=percona-release state=absent

  - name: remove saved repo files in yum
    file: path={{ item }} state=absent
    with_items:
      - /etc/yum.repos.d/percona-release.repo
      - /etc/yum.repos.d/percona-release.repo.rpmsave
      - /etc/yum.repos.d/percona-original-release.repo
      - /etc/yum.repos.d/percona-original-release.repo.rpmsave
      - /etc/yum.repos.d/percona-original-testing.repo
      - /etc/yum.repos.d/percona-original-testing.repo.rpmsave

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_distribution_major_version == "8"

  - name: add the Percona testing yum repos for centos 6 and 7
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm

  - name: enable the PS-80 main repo
    command: percona-release setup ps-80 -y

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
