---
# tasks file for percona-server


  # This removes any percona repositories on the system
  - name: remove the Percona apt main repository
    apt: name=percona-release state=absent
    when: ansible_os_family == "Debian"

  - name: remove the Percona yum repositories
    yum: name=percona-release state=absent
    when: ansible_os_family == "RedHat"

  - name: remove saved repo files in yum
    file: path={{ item }} state=absent
    with_items:
      - /etc/yum.repos.d/percona-release.repo
      - /etc/yum.repos.d/percona-release.repo.rpmsave
      - /etc/yum.repos.d/percona-original-release.repo
      - /etc/yum.repos.d/percona-original-release.repo.rpmsave
      - /etc/yum.repos.d/percona-original-testing.repo
      - /etc/yum.repos.d/percona-original-testing.repo.rpmsave
    when: ansible_os_family == "RedHat"

  - name: disable the mysql module on RHEL/CentOS 8
    command: /usr/bin/dnf module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: Install percona repository package
    apt:
      deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    when: ansible_os_family == "Debian"

  - name: add the Percona testing yum repos for centos 6 and 7
    yum: name=https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    when: ansible_os_family == "RedHat"

  - name: enable the PS-80 main repo
    command: percona-release setup ps-80 -y

  - name: clean and update yum cache
    shell: |
      yum clean all
      yum makecache
    when: ansible_os_family == "RedHat"

# This task installs Percona Server 8.0 on CentOS and Debian/Ubuntu
#

  - name: install Percona Server deb packages
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
      - percona-server-server
      - percona-server-test
      - percona-server-dbg
      - percona-server-source
      - percona-server-client
      - percona-server-rocksdb
      - percona-mysql-router
    when: ansible_os_family == "Debian"

  - name: get list of enabled dnf modules on centos 8
    command: dnf module list --enabled
    register: enabled_dnf_modules
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: list enabled dnf modules on centos 8
    debug:
      var: enabled_dnf_modules
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: disable the mysql module on RHEL/CentOS 8
    command: yum module disable mysql -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: disable the mariadb module on RHEL/CentOS 8
    command: yum module disable mariadb -y
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= "8"

  - name: install Percona Server rpm packages
    yum:
      name: "{{ packages }}"
      state: latest
      disablerepo: "epel"
      update_cache: yes
    vars:
      packages:
      - percona-server-server
      - percona-mysql-router
      - percona-server-client
      - percona-server-test
      - percona-server-debuginfo
      - percona-server-devel
      - percona-server-rocksdb
    when: ansible_os_family == "RedHat"
